### ISSUE TITLE
Deploy on plesk

### ISSUE THREAD

**Issue by sunsgs** [strapi-community/strapi-tool-dockerize#94]
## Feature Request

I Am pretty new to docker. I have used this to dockerize my app, I have now to upload the image to plesk (I can only upload images). How can I create an image of what I have in docker compose?  Do I have to load all immages seperately (oone from my strapi, one for my db ecc) and launch them all toghetere (so do not use docker-compose?)

Thanks

**Comment by Eventyret** [comment]
Hi and glad you got to use the tool
Suggest watch a video from mosh
https://www.youtube.com/watch?v=pTFZFxd4hOI

This teaches the basics of docker as this tool does not provide this type of support, it's there to create the file instead of you do it. But the video should explain how to make images etc.
